### ISSUE TITLE
训练所用的两千五百多万实体来源是哪里呢？百科么？

### ISSUE THREAD

**Issue by jotline** [ownthink/robot#1]

**Comment by ownthink** [comment]
对的，各大百科，不过还有垂直领域的数据，如音乐、电影、字典等等，没全部放出来。

**Comment by ownthink** [comment]
你可以关注下另外一个知识图谱项目：https://github.com/ownthink/KnowledgeGraph

**Comment by jotline** [comment]
@ownthink 好的谢谢你。

**Comment by ownthink** [comment]
@jotline 不客气哈
