### ISSUE TITLE
添加自定义的对话服务

### ISSUE THREAD

**Issue by nullgogo** [ownthink/robot#12]
您好，请问我想调用自己搭建的机器人对话服务，应该如何改啊？
我将bot.js里的url改成我自己的服务，但是打开index.html，输入信息，没有回复。
![image](https://user-images.githubusercontent.com/52397681/156312226-48549928-fb16-4402-bad8-3b4b63aee8e4.png)

**Comment by ownthink** [comment]
不是改url，是改appid




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 下午3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ownthink/robot] 添加自定义的对话服务 (Issue #12)





 
您好，请问我想调用自己搭建的机器人对话服务，应该如何改啊？
 我将bot.js里的url改成我自己的服务，但是打开index.html，输入信息，没有回复。
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nullgogo** [comment]
我这边自己搭建了个底层对话服务，想借助你们的Web 上课展示一下的，请问应该怎么改啊

**Comment by nullgogo** [comment]
可否帮忙看一下如何更改，感谢！

**Comment by ownthink** [comment]
&nbsp;这个我就不知道咯，最好不要使用自己搭建的服务。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ownthink/robot] 添加自定义的对话服务 (Issue #12)





 
我这边自己搭建了个底层对话服务，想借助你们的Web 上课展示一下的，请问应该怎么改啊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nullgogo** [comment]
因为我自己搭建的这个对话服务 是面向校园学生的，上课的时候需要给学生们展示一下，所以想弄一个web展示，直接在命令行展示不怎么美观。

**Comment by ownthink** [comment]
明白，但是你们自己搭建的服务，我们没看到你们的代码，根本无法排查问题啊，可以问下你们学校会前端的老师呢。

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ownthink/robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ownthink/robot] 添加自定义的对话服务 (Issue #12)





 
因为我自己搭建的这个对话服务 是面向校园学生的，上课的时候需要给学生们展示一下，所以想弄一个web展示，直接在命令行展示不怎么美观。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChuangqHu** [comment]
学校里没有专门教学前端这一块的老师，我是自动化专业的，目前是在做校园学生情感咨询领域的对话机器人。
现在我是搭建的flask服务，为了能匹配Web，我搭建的服务 传参和出参都是按照ownthink的样式写的。
上面是ownthink的服务，下面是我搭建的服务

![image](https://user-images.githubusercontent.com/52397681/156317478-7ec23a98-70a9-46bb-a297-9d27bed5209b.png)

![image](https://user-images.githubusercontent.com/52397681/156317862-3f90d352-9a15-408f-9944-16603da6a465.png)
