### ISSUE TITLE
返回结果错误啊

### ISSUE THREAD

**Issue by Zengpr** [ownthink/robot#2]
curl -XPOST https://api.ownthink.com/bot  -d'
{
"appid":"我的apiid",
"spoken":"苏大校长是谁？"
}
'
返回结果为：
{
    "data": "",
    "message": "error"
}

**Comment by ownthink** [comment]
> curl -XPOST https://api.ownthink.com/bot -d'
> {
> "appid":"我的apiid",
> "spoken":"苏大校长是谁？"
> }
> '
> 返回结果为：
> {
> "data": "",
> "message": "error"
> }

appid填写有正确嘛，可以检查下的，调试的时候其实可以先填写appid为openbot的。

**Comment by Zengpr** [comment]
就申请那里直接复制过来的，get方式也不行

**Comment by ownthink** [comment]
curl -XPOST https://api.ownthink.com/bot  -d'
> {
> "appid":"openbot",
> "spoken":"姚明多高啊？"
> }
> '
{
    "message": "success",
    "data": {
        "type": 5000,
        "info": {
            "text": "姚明的身高是226厘米"
        }
    }
}


我这可以额，你再试试看现在可以不，可以加我微信我帮你查看日志定位下 MrYener

**Comment by Zengpr** [comment]
现在都可以了，刚刚不行
